### ISSUE TITLE
getProjects() controller

### ISSUE THREAD

**Issue by sharethewisdom** [Reflex2468/CoolestProjects2019#1]
https://github.com/Reflex2468/CoolestProjects2019/blob/8aaf79ca0fb85d236883b4e54aaf2992b01665c0/app/Http/Controllers/IndexController.php#L33
Zullen we door middel van `file_get_contents('https://scratch.mit.edu/projects/XXXXXXXXX')` html kunnen parsen (titel, beschrijving, instructies?)?

We kunnen de afbeelding hotlinken naar "https://cdn2.scratch.mit.edu/get_image/project/XXXXXXXXX_NNNxNNN.png".

Ik ben niet veel online en heb het druk deze week, maar ik zal proberen te helpen... zijn de laatste wijzigingen gepushed?

**Comment by Reflex2468** [comment]
Ik heb de laatste wijzigingen gepushed.

HTML parsen in php kan. (native: https://www.php.net/manual/en/domdocument.loadhtml.php of via laravel (makkelijker): https://packagist.org/packages/ammadeuss/laravel-html-dom-parser) 

Als we de laravel package zouden gebruiken moeten we die nog installeren
`composer require ammadeuss/laravel-html-dom-parser`
dit zou het wel makkelijker maken om de juiste elementen uit de dom te vinden dan als we met native php zouden werken.

**Comment by Reflex2468** [comment]
Ik heb ontdekt dat scratch een API heeft, we kunnen dus automatisch de projecten toevoegen zonder uberhaupt een link op te geven! https://en.scratch-wiki.info/wiki/Scratch_API_(2.0)

**Comment by sharethewisdom** [comment]
Ok! (... maar is het nog de bedoeling dat de gebruiker projecten selecteert om toe te voegen? Of dat ze gewoon allemaal worden toegevoegd?)

**Comment by Reflex2468** [comment]
Marijke en Jo vonden het beter als ze zelf projecten konden selecteren omdat niet elk project af is, en dus niet elk project er moet opstaan.
